import { FoodItem } from "./store";

export const FOOD_DATABASE: FoodItem[] = [
  { id: "1", name: "Chicken Breast (cooked)", calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sodium: 74, servingSize: "100", servingUnit: "g" },
  { id: "2", name: "Brown Rice (cooked)", calories: 216, protein: 5, carbs: 45, fat: 1.8, fiber: 3.5, sodium: 10, servingSize: "1 cup", servingUnit: "cup" },
  { id: "3", name: "Egg (whole, large)", calories: 72, protein: 6.3, carbs: 0.4, fat: 5, fiber: 0, sodium: 71, servingSize: "1 large", servingUnit: "egg" },
  { id: "4", name: "Banana", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sodium: 1, servingSize: "1 medium", servingUnit: "medium" },
  { id: "5", name: "Greek Yogurt (plain, non-fat)", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, sodium: 36, servingSize: "100", servingUnit: "g" },
  { id: "6", name: "Oatmeal (rolled oats)", calories: 307, protein: 11, carbs: 55, fat: 5, fiber: 8, sodium: 2, servingSize: "100", servingUnit: "g" },
  { id: "7", name: "Salmon (cooked)", calories: 208, protein: 29, carbs: 0, fat: 9.2, fiber: 0, sodium: 59, servingSize: "100", servingUnit: "g" },
  { id: "8", name: "Spinach (raw)", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sodium: 79, servingSize: "100", servingUnit: "g" },
  { id: "9", name: "Almonds", calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5, sodium: 1, servingSize: "100", servingUnit: "g" },
  { id: "10", name: "Sweet Potato (cooked)", calories: 90, protein: 2, carbs: 21, fat: 0.1, fiber: 3.3, sodium: 36, servingSize: "100", servingUnit: "g" },
  { id: "11", name: "Broccoli (cooked)", calories: 35, protein: 2.4, carbs: 7.2, fat: 0.4, fiber: 3.3, sodium: 41, servingSize: "100", servingUnit: "g" },
  { id: "12", name: "Whole Milk", calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sodium: 43, servingSize: "100", servingUnit: "ml" },
  { id: "13", name: "White Bread", calories: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, sodium: 491, servingSize: "1 slice", servingUnit: "slice" },
  { id: "14", name: "Apple", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sodium: 1, servingSize: "1 medium", servingUnit: "medium" },
  { id: "15", name: "Cheddar Cheese", calories: 402, protein: 25, carbs: 1.3, fat: 33, fiber: 0, sodium: 621, servingSize: "100", servingUnit: "g" },
  { id: "16", name: "Tuna (canned in water)", calories: 116, protein: 25.5, carbs: 0, fat: 1, fiber: 0, sodium: 320, servingSize: "100", servingUnit: "g" },
  { id: "17", name: "Lentils (cooked)", calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 7.9, sodium: 238, servingSize: "100", servingUnit: "g" },
  { id: "18", name: "Avocado", calories: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, sodium: 7, servingSize: "100", servingUnit: "g" },
  { id: "19", name: "Orange", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, sodium: 0, servingSize: "1 medium", servingUnit: "medium" },
  { id: "20", name: "Protein Whey Shake", calories: 120, protein: 25, carbs: 4, fat: 2, fiber: 0, sodium: 100, servingSize: "1 scoop", servingUnit: "scoop" },
  { id: "21", name: "Blueberries", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, sodium: 1, servingSize: "100", servingUnit: "g" },
  { id: "22", name: "Quinoa (cooked)", calories: 120, protein: 4.4, carbs: 21.3, fat: 1.9, fiber: 2.8, sodium: 7, servingSize: "100", servingUnit: "g" },
  { id: "23", name: "Olive Oil", calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 2, servingSize: "1 tbsp", servingUnit: "tbsp" },
  { id: "24", name: "Black Coffee", calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, sodium: 5, servingSize: "240", servingUnit: "ml" },
  { id: "25", name: "Orange Juice (fresh)", calories: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, sodium: 1, servingSize: "100", servingUnit: "ml" },
];

export const WORKOUT_EXERCISES = [
  { name: "Push-ups", category: "Chest", muscles: ["Chest", "Triceps", "Shoulders"] },
  { name: "Pull-ups", category: "Back", muscles: ["Back", "Biceps"] },
  { name: "Squats", category: "Legs", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { name: "Deadlift", category: "Full Body", muscles: ["Back", "Glutes", "Hamstrings", "Core"] },
  { name: "Bench Press", category: "Chest", muscles: ["Chest", "Triceps"] },
  { name: "Overhead Press", category: "Shoulders", muscles: ["Shoulders", "Triceps"] },
  { name: "Bicep Curls", category: "Arms", muscles: ["Biceps"] },
  { name: "Tricep Dips", category: "Arms", muscles: ["Triceps"] },
  { name: "Plank", category: "Core", muscles: ["Core", "Abs"] },
  { name: "Lunges", category: "Legs", muscles: ["Quads", "Glutes"] },
  { name: "Running", category: "Cardio", muscles: ["Full Body"] },
  { name: "Cycling", category: "Cardio", muscles: ["Legs", "Cardio"] },
  { name: "Jump Rope", category: "Cardio", muscles: ["Full Body", "Cardio"] },
  { name: "Burpees", category: "Full Body", muscles: ["Full Body", "Cardio"] },
  { name: "Mountain Climbers", category: "Core", muscles: ["Core", "Cardio"] },
  { name: "Lat Pulldown", category: "Back", muscles: ["Back", "Biceps"] },
  { name: "Leg Press", category: "Legs", muscles: ["Quads", "Glutes"] },
  { name: "Cable Row", category: "Back", muscles: ["Back", "Biceps"] },
  { name: "Shoulder Lateral Raise", category: "Shoulders", muscles: ["Shoulders"] },
  { name: "Leg Curl", category: "Legs", muscles: ["Hamstrings"] },
];
